import"./assets/modal-window-f337a4f1.js";import{a as u,i as T}from"./assets/vendor-59c8246b.js";async function E(){const t="https://books-backend.p.goit.global/books/category-list",e={method:"GET"};return(await u.get(t,{options:e})).data}async function S(t){const e="https://books-backend.p.goit.global/books/category",o=encodeURIComponent(t),s=`${e}?category=${o}`,c={method:"GET",headers:{"Content-Type":"application/json"}};return(await u.get(s,c)).data}async function g(t,e){const o="https://books-backend.p.goit.global/books/top-books",s=encodeURIComponent(t);let c;e?c=`${o}?category=${s}&limit=${e}`:c=`${o}?category=${s}`;const r={method:"GET",headers:{"Content-Type":"application/json"}};return(await u.get(c,r)).data}const h=document.querySelector(".books-container-one-cat"),i=document.querySelector(".books-container-all-cat-block"),p=document.querySelector(".books-container-all-cat-title"),a=window.innerWidth;let n;function w(t){return`<div class="book-item">
  <ul class="book-item-block">
    <li class="book-item-img">
      <img
        src="${t.book_image}"
        alt="${t.description}"
        srcset="${t.book_image}"
        width="335"
        height="485"
        class="book-image"
      />
      <p class="hidden-overflow">QUICK VIEW</p>
    </li>
    <li class="book-item-title">${t.title}</li>
    <li class="book-item-author">${t.author}</li>
  </ul>
</div>`}function y(t){return t.map(w).join("")}function $(t,e){h.innerHTML="",i.innerHTML="",p.innerHTML="";const s=e.split(" "),c=s.pop(),r=`<h3 class="container-category-one">${s.join(" ")+' <span class="last-word">'+c+"</span>"}</h3><div class="books-container-one-cat-block">${y(t)}</div>`;h.innerHTML=r}function b(t){h.innerHTML="",i.innerHTML="";const e='<h2 class="container-title">Best Sellers <span>Book</span></h2>';let o="";t.forEach(s=>{o+=`<div class="cat-books-btn">
      <h3 class="container-category-all">${s.list_name}</h3>
    <div class="books-container-all-cat-block-bpt">${y(s.books)}</div>
    <button type="button" class="btn-seemore hidden" data-category="${s.list_name}">SEE MORE</button>
    </div>`}),p.innerHTML=e,i.innerHTML=o}async function A(t){try{const e=await S(t);$(e,t),handleBookClick()}catch{k("Sorry, there are no books for these category! ","red","white")}}async function f(t){try{if(a>=375&&a<=767)n=1;else if(a>=768&&a<1158)n=3;else{n=5;return}let e=await g(t,n);e=e.map(o=>(o.books=o.books.slice(0,n),o)),b(e),L()}catch{k("Sorry, no books! ","red","white")}}function L(){n===1||n===3?M():v()}function M(){if(n<=5){const t=document.querySelectorAll(".btn-seemore");for(let e=0;e<t.length;e++)t[e].classList.remove("hidden")}}function v(){if(n>=5){const t=document.querySelectorAll(".btn-seemore");for(let e=0;e<t.length;e++)t[e].classList.add("hidden")}}async function H(t,e){try{if(a>=375&&a<=767)n=1,n+=4;else if(a>=768&&a<1158)n=3,n+=2;else return;let o=await g(e,n);o=o.map(s=>(s.books=s.books.slice(0,n),s)),b(o),L(),handleBookClick(t)}catch{k("Sorry, no books! ","red","white")}}i.addEventListener("click",async t=>{if(t.target&&t.target.classList.contains("btn-seemore")){t.preventDefault();const e=t.target.dataset.category;await H(t,e)}});function k(t,e,o){T.error({position:"topRight",message:t,messageColor:o,messageSize:"16",messageLineHeight:"15",backgroundColor:e,timeout:5e3,displayMode:2,close:!0,closeOnEscape:!0,closeOnClick:!0})}const q=document.querySelector("#category-list");let C;window.onload=function(){const t=document.getElementById("category-list"),e=document.createElement("li");e.textContent="ALL CATEGORIES",e.id="title",t.appendChild(e),E().then(o=>{o.forEach(function(s){const c=document.createElement("p");c.textContent=s.list_name,c.classList.add("p-list"),t.appendChild(c)})}).catch(o=>{console.error("Error fetching data;",o)}),f(C)};q.addEventListener("click",async t=>{if(t.preventDefault(),t.target.tagName==="P"){const e=t.target.textContent;A(e)}else t.target.id==="title"&&f(C)});const l=document.querySelector("#slider"),B=document.querySelector("#theme-style");let m=localStorage.getItem("theme");m&&B.setAttribute("href",`./css/${m}.css`);function d(t){localStorage.setItem("theme",t),B.setAttribute("href",`./css/${t}.css`)}function I(){l.checked?d("styles-light-theme"):d("styles-dark-theme")}l.addEventListener("change",I);function R(){m==="styles-dark-theme"?(d("styles-dark-theme"),l.checked=!1):(d("styles-light-theme"),l.checked=!0)}R();
//# sourceMappingURL=commonHelpers.js.map
